package is.morozov.structurizr;

import com.structurizr.dsl.StructurizrDslPlugin;
import com.structurizr.dsl.StructurizrDslPluginContext;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

public class EmbedViewsExtractorPlugin implements StructurizrDslPlugin {

    private static final Pattern CODE_BLOCK_PATTERN = Pattern.compile(
            "```structurizr\\{embed\\}\\s*\\n(.*?)```",
            Pattern.DOTALL
    );

    @Override
    public void run(StructurizrDslPluginContext context) {
        String directory = context.getParameter("path", "docs");
        String outputFile = context.getParameter("output", "embedded-views.dsl");

        File baseDir = new File(context.getDslFile().getParentFile(), directory);
        File output = new File(context.getDslFile().getParentFile(), outputFile);

        if (!baseDir.exists() || !baseDir.isDirectory()) {
            System.err.println("EmbedViewsExtractor: Directory not found: " + baseDir.getAbsolutePath());
            return;
        }

        List<ViewDefinition> viewDefinitions = extractViewDefinitionsFromMarkdown(baseDir);

        String content = viewDefinitions.isEmpty()
                ? "# Auto-generated by EmbedViewsExtractorPlugin - no embedded views found\n"
                : buildDslContent(viewDefinitions);

        try {
            if (output.getParentFile() != null) {
                output.getParentFile().mkdirs();
            }
            Files.writeString(output.toPath(), content);
        } catch (IOException e) {
            System.err.println("EmbedViewsExtractor: Failed to write output file: " + e.getMessage());
        }
    }

    private List<ViewDefinition> extractViewDefinitionsFromMarkdown(File directory) {
        List<ViewDefinition> definitions = new ArrayList<>();

        try (Stream<Path> paths = Files.walk(directory.toPath())) {
            paths.filter(Files::isRegularFile)
                    .filter(p -> p.toString().endsWith(".md"))
                    .sorted()
                    .forEach(path -> {
                        try {
                            String content = Files.readString(path);
                            Matcher matcher = CODE_BLOCK_PATTERN.matcher(content);
                            while (matcher.find()) {
                                definitions.add(new ViewDefinition(
                                        path.getFileName().toString(),
                                        matcher.group(1).trim()
                                ));
                            }
                        } catch (IOException e) {
                            System.err.println("EmbedViewsExtractor: Failed to read file: " + path);
                        }
                    });
        } catch (IOException e) {
            System.err.println("EmbedViewsExtractor: Failed to walk directory: " + directory);
        }

        return definitions;
    }

    private String buildDslContent(List<ViewDefinition> definitions) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by EmbedViewsExtractorPlugin - DO NOT EDIT\n\n");

        String currentSource = null;
        for (ViewDefinition def : definitions) {
            if (!def.sourceFile.equals(currentSource)) {
                if (currentSource != null) {
                    sb.append("\n");
                }
                sb.append("# From: ").append(def.sourceFile).append("\n");
                currentSource = def.sourceFile;
            }
            sb.append(def.content).append("\n");
        }

        return sb.toString();
    }

    private record ViewDefinition(String sourceFile, String content) {}
}
